name: Node.js
on:
  push:
    paths:
      - ".github/workflows/nodejs-Workflow.yml"
permissions:
  security-events: write
  actions: read
  issues: write
  contents: read
jobs:
  Build-Test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: setup nodejs
        uses: actions/setup-node@v6
        with:
          node-version: '24'
      - name: build
        run: npm install
      - name: test
        run: npm test
      - name: cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: artifact upload
        uses: actions/upload-artifact@v4
        with:
          name: artifact-1
          path: |
            package*
      - name: deploy
        run: echo "code is deployed"
      - name: Send Success Email
        if: success()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Workflow Succeeded"
          to: madhuri14sangam@gmail.com
          from: GitHub Actions
          body: |  
            Workflow: ${{ github.workflow }}
            Repository: ${{ github.repository }}
            Branch: ${{ github.ref_name }}
            Status: Workflow completed successfully.
            Commit: ${{ github.sha }}   

        
