name: Terraform-CI
on:
 workflow_dispatch: 
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: "us-east-2"
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
     - name: checkout code
       uses: actions/checkout@v7
     - name: Setup Terraform
       uses: hashicorp/setup-terraform@v4
       with: 
         terraform_version: '1.15.6'
     - name: Terraform init  
       run: terraform init
     - name: Terraform Validate
       run: terraform validate
     - name: Terraform Plan
       run: terraform plan
     - name: Terraform Apply
       run: terraform apply -auto-approve
     - name: Send Success Email
       if: success()
       uses: dawidd6/action-send-mail@v3
       with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Workflow Succeeded"
          to: madhuri14sangam@gmail.com
          from: GitHub Actions
          body: |  
            Workflow: ${{ github.workflow }}
            Repository: ${{ github.repository }}
            Branch: ${{ github.ref_name }}
            Status: Workflow completed successfully.
            Commit: ${{ github.sha }}    
